//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresseDeLivraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdresseDeLivraison()
        {
            this.BonLivraison = new HashSet<BonLivraison>();
        }
    
        public int code_adresse_livraison { get; set; }
        public string adresse_livraison { get; set; }
        public string code_postal_livraison { get; set; }
        public string ville_livraison { get; set; }
        public string pays_livraison { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonLivraison> BonLivraison { get; set; }
    }
}
