//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonLivraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonLivraison()
        {
            this.regroupe = new HashSet<regroupe>();
        }
    
        public int code_livraison { get; set; }
        public System.DateTime date_livraison { get; set; }
        public int code_adresse_livraison { get; set; }
        public int numero_commande { get; set; }
    
        public virtual AdresseDeLivraison AdresseDeLivraison { get; set; }
        public virtual Commande Commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regroupe> regroupe { get; set; }
    }
}
